# Generated by Django 4.2.5 on 2024-01-31 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forumapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussionthread',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
